function fileLanguageMapper(extension: string): string {
    const mapping: { [key: string]: string } = {
        'bat': 'bat',
        'cmd': 'bat',
        'bib': 'bibtex',
        'clj': 'clojure',
        'cljs': 'clojure',
        'coffee': 'coffeescript',
        'cson': 'coffeescript',
        'iced': 'coffeescript',
        'cpp': 'cpp',
        'cc': 'cpp',
        'cxx': 'cpp',
        'h': 'cpp',
        'hh': 'cpp',
        'hpp': 'cpp',
        'cs': 'csharp',
        'css': 'css',
        'dockerfile': 'dockerfile',
        'fs': 'fsharp',
        'fsi': 'fsharp',
        'ml': 'fsharp',
        'mli': 'fsharp',
        'go': 'go',
        'groovy': 'groovy',
        'handlebars': 'handlebars',
        'hbs': 'handlebars',
        'html': 'html',
        'ini': 'ini',
        'java': 'java',
        'jsp': 'java',
        'js': 'javascript',
        'cjs': 'javascript',
        'mjs': 'javascript',
        'json': 'json',
        'jsonc': 'jsonc',
        'jl': 'julia',
        'kt': 'kotlin',
        'less': 'less',
        'lua': 'lua',
        'md': 'markdown',
        'markdown': 'markdown',
        'm': 'objective-c',
        'mm': 'objective-c',
        'pl': 'perl',
        'php': 'php',
        'phtml': 'php',
        'php4': 'php',
        'php5': 'php',
        'phps': 'php',
        'phpt': 'php',
        'ps1': 'powershell',
        'psm1': 'powershell',
        'psd1': 'powershell',
        'py': 'python',
        'r': 'r',
        'rmd': 'r',
        'rb': 'ruby',
        'rs': 'rust',
        'scss': 'scss',
        'sh': 'shell',
        'bash': 'shell',
        'zsh': 'shell',
        'sql': 'sql',
        'st': 'smalltalk',
        'swift': 'swift',
        'ts': 'typescript',
        'tsx': 'typescript',
        'vb': 'vb',
        'xml': 'xml',
        'xsd': 'xml',
        'ascx': 'xml',
        'csproj': 'xml',
        'config': 'xml',
        'wxi': 'xml',
        'wxl': 'xml',
        'wxs': 'xml',
        'svg': 'svg',
        'yaml': 'yaml',
        'yml': 'yaml'
    };

    return mapping[extension] || 'plaintext';
}

export default fileLanguageMapper;
